"""Kubernetes models as dataclasses copied from k8s' OpenAPI V3 Spec."""

from gybe.k8s.types import K8sSpec
from gybe.k8s.v1_30.apps.v1 import (
    DaemonSet,
    DaemonSetSpec,
    Deployment,
    DeploymentSpec,
    DeploymentStrategy,
    StatefulSet,
    StatefulSetSpec,
)
from gybe.k8s.v1_30.batch.v1 import Job, JobSpec
from gybe.k8s.v1_30.core.v1 import (
    Affinity,
    Container,
    ContainerPort,
    EnvFromSource,
    EnvVar,
    EnvVarSource,
    HTTPGetAction,
    ObjectFieldSelector,
    PersistentVolume,
    PersistentVolumeClaim,
    PersistentVolumeClaimSpec,
    PersistentVolumeSpec,
    Pod,
    PodAffinityTerm,
    PodAntiAffinity,
    PodSpec,
    PodTemplateSpec,
    Probe,
    ResourceRequirements,
    Secret,
    SecretEnvSource,
    SecretKeySelector,
    SecretVolumeSource,
    SecurityContext,
    Service,
    ServicePort,
    ServiceSpec,
    Volume,
    VolumeMount,
    VolumeResourceRequirements,
    WeightedPodAffinityTerm,
)
from gybe.k8s.v1_30.meta.v1 import LabelSelector, LabelSelectorRequirement, ObjectMeta
from gybe.k8s.v1_30.networking.v1 import (
    Ingress,
    IngressBackend,
    IngressServiceBackend,
    IngressSpec,
    ServiceBackendPort,
)

__all__ = [
    'K8sSpec',
    'LabelSelector',
    'LabelSelectorRequirement',
    'Affinity',
    'PodAntiAffinity',
    'ContainerPort',
    'WeightedPodAffinityTerm',
    'PodAffinityTerm',
    'Deployment',
    'DeploymentSpec',
    'StatefulSet',
    'StatefulSetSpec',
    'Job',
    'JobSpec',
    'DaemonSet',
    'DaemonSetSpec',
    'Pod',
    'PodSpec',
    'Container',
    'Secret',
    'SecretEnvSource',
    'ResourceRequirements',
    'EnvVar',
    'Ingress',
    'IngressSpec',
    'IngressBackend',
    'IngressServiceBackend',
    'IngressServiceBackendPort',
    'ServiceBackendPort',
    'EnvFromSource',
    'EnvVarSource',
    'ObjectFieldSelector',
    'SecurityContext',
    'Probe',
    'HTTPGetAction',
    'Service',
    'ServiceSpec',
    'ObjectMeta',
    'PersistentVolume',
    'PersistentVolumeSpec',
    'PersistentVolumeClaim',
    'PersistentVolumeClaimSpec',
    'VolumeMount',
    'SecretKeySelector',
    'ServicePort',
    'DeploymentStrategy',
    'PodTemplateSpec',
    'Volume',
    'SecretVolumeSource',
    'PersistentVolumeClaimSpec',
    'VolumeResourceRequirements',
]
