#!/usr/bin/env bash
set -e

(cd kubernetes && git checkout master -q && git pull -q)

function gen_k8s() {
  local version="$1"
  local version_module="$2"
  (cd kubernetes && git checkout $version -q)
  rm -rf gybe/kubernetes/$version_module
  python -m gybe.codegen $version_module
  ruff check --quiet --fix gybe/k8s/v*
  ruff format --quiet gybe/k8s/v*
  (cd kubernetes && git checkout master -q)
}

# https://kubernetes.io/releases/
gen_k8s 'v1.26.15' 'v1_26'
gen_k8s 'v1.27.16' 'v1_27'
gen_k8s 'v1.28.12' 'v1_28'
gen_k8s 'v1.29.7' 'v1_29'
gen_k8s 'v1.30.3' 'v1_30'

(cd kubernetes && git checkout master -q)
