#!/usr/bin/env bash
set -e

(cd kubernetes && git checkout master -q && git pull -q)

function gen_k8s() {
  local version="$1"
  local version_module="$2"
  (cd kubernetes && git checkout $version -q)
  mkdir -p tests/data/k8s-api-specs/$version
  python -m gybe.codegen $version_module
  ruff check --quiet --fix gybe/k8s/v*
  ruff format --quiet gybe/k8s/v*
  (cd kubernetes && git checkout master -q)
}

# https://kubernetes.io/releases/
gen_k8s 'v1.29.13' 'v1_29'
gen_k8s 'v1.30.9' 'v1_30'
gen_k8s 'v1.31.5' 'v1_31'
gen_k8s 'v1.32.1' 'v1_32'

(cd kubernetes && git checkout master -q)
