# generated by datamodel-codegen:
#   filename:  _definitions.json
#   timestamp: 2021-01-20T05:35:16+00:00

from __future__ import annotations

from pydantic import BaseModel


class RawExtension(BaseModel):
    pass
