# generated by datamodel-codegen:
#   filename:  v3
#   timestamp: 2022-10-03T01:54:43+00:00

from __future__ import annotations

from pydantic import BaseModel


class RawExtension(BaseModel):
    pass


class RawExtensionModel(BaseModel):
    pass


class RawExtensionModel1(BaseModel):
    pass


class RawExtensionModel2(BaseModel):
    pass


class RawExtensionModel3(BaseModel):
    pass


class RawExtensionModel4(BaseModel):
    pass


class RawExtensionModel5(BaseModel):
    pass


class RawExtensionModel6(BaseModel):
    pass


class RawExtensionModel7(BaseModel):
    pass


class RawExtensionModel8(BaseModel):
    pass


class RawExtensionModel9(BaseModel):
    pass


class RawExtensionModel10(BaseModel):
    pass


class RawExtensionModel11(BaseModel):
    pass


class RawExtensionModel12(BaseModel):
    pass


class RawExtensionModel13(BaseModel):
    pass


class RawExtensionModel14(BaseModel):
    pass


class RawExtensionModel15(BaseModel):
    pass


class RawExtensionModel16(BaseModel):
    pass


class RawExtensionModel17(BaseModel):
    pass


class RawExtensionModel18(BaseModel):
    pass


class RawExtensionModel19(BaseModel):
    pass
