# generated by datamodel-codegen:
#   filename:  v3
#   timestamp: 2023-01-30T23:30:42+00:00

from __future__ import annotations

from pydantic import BaseModel


class RawExtension(BaseModel):
    pass
